openapi: 3.0.0
info:
  title: AWS AI Concierge Tools
  version: 1.0.0
  description: Tools for AWS resource management and monitoring

paths:
  /cost-analysis:
    post:
      summary: Analyze AWS costs and spending patterns
      operationId: getCostAnalysis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                time_period:
                  type: string
                  description: Time period for cost analysis
              required: ["time_period"]
      responses:
        '200':
          description: Cost analysis results
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_cost:
                    type: number
                  currency:
                    type: string